import { useState } from "react";
import { Link as RouterLink, useNavigate } from "react-router-dom";
import { Alert, Box, Button, Checkbox, FormControlLabel, IconButton, InputAdornment, Link, Stack, TextField, Typography } from "@mui/material";
import VisibilityOutlinedIcon from "@mui/icons-material/VisibilityOutlined";
import VisibilityOffOutlinedIcon from "@mui/icons-material/VisibilityOffOutlined";
import ArrowForwardIcon from "@mui/icons-material/ArrowForward";
import AuthLayout from "../components/auth/AuthLayout";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../components/common/ToastProvider";

const emailError = (email) => !email.trim() ? "Email is required" : !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) ? "Enter a valid email address" : "";
const passwordError = (password) => !password ? "Password is required" : "";

const LoginPage = () => {
  const { login } = useAuth(); const { showToast } = useToast(); const navigate = useNavigate(); const [form, setForm] = useState({ email: "", password: "" }); const [errors, setErrors] = useState({}); const [apiError, setApiError] = useState(""); const [loading, setLoading] = useState(false); const [showPassword, setShowPassword] = useState(false); const [rememberMe, setRememberMe] = useState(false);
  const updateField = (field, value) => { const next = { ...form, [field]: value }; setForm(next); setApiError(""); setErrors((current) => ({ ...current, [field]: field === "email" ? emailError(next.email) : passwordError(next.password) })); };
  const validate = () => { const next = { email: emailError(form.email), password: passwordError(form.password) }; setErrors(next); return !next.email && !next.password; };
  const handleSubmit = async (event) => { event.preventDefault(); setApiError(""); if (!validate()) return; setLoading(true); try { await login(form.email.trim(), form.password); showToast("Signed in successfully."); navigate("/dashboard"); } catch (err) { const message = err?.response?.data?.message || "Login failed. Please try again."; setApiError(message); showToast(message, "error"); } finally { setLoading(false); } };
  const fieldStyle = { "& .MuiOutlinedInput-root": { borderRadius: 1 } };
  return <AuthLayout eyebrow="SIGN IN" title="Welcome back" subtitle="Sign in to access your workspace.">{apiError && <Alert severity="error" sx={{ mb: 2 }}>{apiError}</Alert>}<Box component="form" onSubmit={handleSubmit} noValidate><Typography component="label" htmlFor="email" display="block" fontWeight={600} fontSize="0.9rem" mb={0.9}>Email address</Typography><TextField id="email" type="email" placeholder="you@example.com" fullWidth value={form.email} onChange={(event) => updateField("email", event.target.value)} error={Boolean(errors.email)} helperText={errors.email || "Enter your account email."} autoFocus sx={{ ...fieldStyle, mb: 2.25 }} /><Typography component="label" htmlFor="password" display="block" fontWeight={600} fontSize="0.9rem" mb={0.9}>Password</Typography><TextField id="password" type={showPassword ? "text" : "password"} placeholder="Enter your password" fullWidth value={form.password} onChange={(event) => updateField("password", event.target.value)} error={Boolean(errors.password)} helperText={errors.password} sx={fieldStyle} InputProps={{ endAdornment: <InputAdornment position="end"><IconButton aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword((value) => !value)} edge="end">{showPassword ? <VisibilityOffOutlinedIcon /> : <VisibilityOutlinedIcon />}</IconButton></InputAdornment> }} /><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", sm: "1fr auto" }, alignItems: "center", columnGap: 2, rowGap: 0.5, width: "100%", mt: 1.25, mb: 2.25 }}><FormControlLabel control={<Checkbox checked={rememberMe} onChange={(event) => setRememberMe(event.target.checked)} />} label="Remember me" sx={{ m: 0, color: "text.secondary", "& .MuiFormControlLabel-label": { fontSize: "0.9rem" } }} /><Link component={RouterLink} to="/forgot-password" underline="hover" color="primary.main" fontSize="0.9rem" fontWeight={600} sx={{ whiteSpace: "nowrap", justifySelf: { sm: "end" } }}>Forgot password?</Link></Box><Button type="submit" fullWidth variant="contained" size="large" disabled={loading} endIcon={!loading && <ArrowForwardIcon />} sx={{ py: 1.45, borderRadius: 1, fontSize: "1rem" }}>{loading ? "Signing in..." : "Sign in"}</Button></Box><Typography variant="body2" textAlign="center" color="text.secondary" mt={3}>Don't have an account? <Link component={RouterLink} to="/register" fontWeight={600} underline="hover">Sign up</Link></Typography></AuthLayout>;
};
export default LoginPage;
