import { useState } from "react";
import { Link as RouterLink, useNavigate } from "react-router-dom";
import { Alert, Box, Button, IconButton, InputAdornment, Link, TextField, Typography } from "@mui/material";
import VisibilityOutlinedIcon from "@mui/icons-material/VisibilityOutlined";
import VisibilityOffOutlinedIcon from "@mui/icons-material/VisibilityOffOutlined";
import ArrowForwardIcon from "@mui/icons-material/ArrowForward";
import AuthLayout from "../components/auth/AuthLayout";
import { useAuth } from "../context/AuthContext";
import { useToast } from "../components/common/ToastProvider";

const emailError = (email) => !email.trim() ? "Email is required" : !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) ? "Enter a valid email address" : "";
const passwordError = (password) => !password ? "Password is required" : password.length < 8 ? "Use at least 8 characters" : !/[a-z]/.test(password) || !/[A-Z]/.test(password) || !/\d/.test(password) || !/[^A-Za-z0-9]/.test(password) ? "Use uppercase, lowercase, number, and symbol" : "";

const RegisterPage = () => {
  const { register } = useAuth(); const { showToast } = useToast(); const navigate = useNavigate(); const [form, setForm] = useState({ full_name: "", email: "", password: "", confirm_password: "" }); const [errors, setErrors] = useState({}); const [apiError, setApiError] = useState(""); const [loading, setLoading] = useState(false); const [showPassword, setShowPassword] = useState(false);
  const fieldError = (field, formData) => field === "full_name" ? (!formData.full_name.trim() ? "Full name is required" : formData.full_name.trim().length < 2 ? "Enter at least 2 characters" : "") : field === "email" ? emailError(formData.email) : field === "password" ? passwordError(formData.password) : (!formData.confirm_password ? "Please confirm your password" : formData.confirm_password !== formData.password ? "Passwords do not match" : "");
  const updateField = (field, value) => { const next = { ...form, [field]: value }; setForm(next); setApiError(""); setErrors((current) => ({ ...current, [field]: fieldError(field, next), ...(field === "password" && { confirm_password: next.confirm_password ? fieldError("confirm_password", next) : current.confirm_password }) })); };
  const validate = () => { const next = Object.fromEntries(["full_name", "email", "password", "confirm_password"].map((field) => [field, fieldError(field, form)])); setErrors(next); return !Object.values(next).some(Boolean); };
  const handleSubmit = async (event) => { event.preventDefault(); setApiError(""); if (!validate()) return; setLoading(true); try { await register(form.full_name.trim(), form.email.trim(), form.password); showToast("Account created successfully."); navigate("/dashboard"); } catch (err) { const message = err?.response?.data?.message || "Registration failed. Please try again."; setApiError(message); showToast(message, "error"); } finally { setLoading(false); } };
  const fieldStyle = { "& .MuiOutlinedInput-root": { borderRadius: 1 } };
  return <AuthLayout eyebrow="CREATE ACCOUNT" title="Get started" subtitle="Create an account to organize your work.">{apiError && <Alert severity="error" sx={{ mb: 2 }}>{apiError}</Alert>}<Box component="form" onSubmit={handleSubmit} noValidate><Typography component="label" htmlFor="full_name" display="block" fontWeight={600} fontSize="0.9rem" mb={0.9}>Full name</Typography><TextField id="full_name" placeholder="Your full name" fullWidth value={form.full_name} onChange={(event) => updateField("full_name", event.target.value)} error={Boolean(errors.full_name)} helperText={errors.full_name} autoFocus sx={{ ...fieldStyle, mb: 2.25 }} /><Typography component="label" htmlFor="email" display="block" fontWeight={600} fontSize="0.9rem" mb={0.9}>Email address</Typography><TextField id="email" type="email" placeholder="you@example.com" fullWidth value={form.email} onChange={(event) => updateField("email", event.target.value)} error={Boolean(errors.email)} helperText={errors.email || "Use a valid email address."} sx={{ ...fieldStyle, mb: 2.25 }} /><Typography component="label" htmlFor="password" display="block" fontWeight={600} fontSize="0.9rem" mb={0.9}>Password</Typography><TextField id="password" type={showPassword ? "text" : "password"} placeholder="Create a strong password" fullWidth value={form.password} onChange={(event) => updateField("password", event.target.value)} error={Boolean(errors.password)} helperText={errors.password || "8+ characters, uppercase, lowercase, number, and symbol."} sx={{ ...fieldStyle, mb: 2.25 }} InputProps={{ endAdornment: <InputAdornment position="end"><IconButton aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword((value) => !value)} edge="end">{showPassword ? <VisibilityOffOutlinedIcon /> : <VisibilityOutlinedIcon />}</IconButton></InputAdornment> }} /><Typography component="label" htmlFor="confirm_password" display="block" fontWeight={600} fontSize="0.9rem" mb={0.9}>Confirm password</Typography><TextField id="confirm_password" type={showPassword ? "text" : "password"} placeholder="Re-enter your password" fullWidth value={form.confirm_password} onChange={(event) => updateField("confirm_password", event.target.value)} error={Boolean(errors.confirm_password)} helperText={errors.confirm_password} sx={fieldStyle} /><Button type="submit" fullWidth variant="contained" size="large" disabled={loading} endIcon={!loading && <ArrowForwardIcon />} sx={{ mt: 3, py: 1.45, borderRadius: 1, fontSize: "1rem" }}>{loading ? "Creating account..." : "Create account"}</Button></Box><Typography variant="body2" textAlign="center" color="text.secondary" mt={3}>Already have an account? <Link component={RouterLink} to="/login" fontWeight={600} underline="hover">Sign in</Link></Typography></AuthLayout>;
};
export default RegisterPage;
